image : microsoft/dotnet:latest
stages:
  - build
  - test
before_script:
  - 'dotnet restore CoursesSystem'
build:
 stage: build
 script:
  - 'dotnet build CoursesSystem'
 test:
 stage: test 
 script:
  - 'dotnet test CoursesSystem/CoursesSystem.Services.Data.UnitTests' 